Ext.define('OA.view.DocWorkflow', {
    extend: 'Ext.Container',
    xtype: "docWorkflow",
    requires: [],
    config: {
        layout: Ext.os.deviceType == 'Phone' ? 'fit' : {
            type: 'fit'
        },
        html: [
            "<table border=0 cellpadding=0 cellspacing=0 width=570 style='border-collapse:",
            "collapse;table-layout:fixed;width:450pt'>",
            "<col width=47 style='mso-width-source:userset;mso-width-alt:1678;width:35pt'>",
            "<col width=64 style='width:48pt'>",
            "<col width=112 style='mso-width-source:userset;mso-width-alt:3982;width:84pt'>",
            "<col width=106 style='mso-width-source:userset;mso-width-alt:3783;width:80pt'>",
            "<col width=114 style='mso-width-source:userset;mso-width-alt:4067;width:86pt'>",
            "<col width=157 style='mso-width-source:userset;mso-width-alt:5575;width:118pt'>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl65 width=47 style='height:30.0pt;width:35pt'>序號</td>",
            "<td class=xl65 width=64 style='width:48pt'>單位</td>",
            "<td class=xl65 width=112 style='width:84pt'>人員</td>",
            "<td class=xl65 width=106 style='width:80pt'>處理時間</td>",
            "<td class=xl65 width=114 style='width:86pt'>動作</td>",
            "<td class=xl65 width=157 style='width:118pt'>&#25933;述</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl66 width=47 style='height:30.0pt;width:35pt'>1</td>",
            "<td class=xl66 width=64 style='border-left:none;width:48pt'>綜合一組</td>",
            "<td class=xl66 width=112 style='border-left:none;width:84pt'>測試自然人1</td>",
            "<td class=xl66 width=106 style='border-left:none;width:80pt'>104/12/23 <br>",
            "09:50:59</td>",
            "<td class=xl66 width=114 style='border-left:none;width:86pt'>創簽稿登錄</td>",
            "<td class=xl66 width=157 style='border-left:none;width:118pt'>　</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl67 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>2</td>",
            "<td class=xl67 width=64 style='border-top:none;border-left:none;width:48pt'>綜合一組</td>",
            "<td class=xl67 width=112 style='border-top:none;border-left:none;width:84pt'>測試自然人1</td>",
            "<td class=xl67 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "09:50:59</td>",
            "<td class=xl67 width=114 style='border-top:none;border-left:none;width:86pt'>承辦人(承辦中)</td>",
            "<td class=xl67 width=157 style='border-top:none;border-left:none;width:118pt'>　</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl66 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>3</td>",
            "<td class=xl66 width=64 style='border-top:none;border-left:none;width:48pt'>綜合一組</td>",
            "<td class=xl66 width=112 style='border-top:none;border-left:none;width:84pt'>測試自然人1</td>",
            "<td class=xl66 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "09:51:54</td>",
            "<td class=xl66 width=114 style='border-top:none;border-left:none;width:86pt'>承辦人(承辦中)</td>",
            "<td class=xl66 width=157 style='border-top:none;border-left:none;width:118pt'>陳核:測試基層主管2</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl67 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>4</td>",
            "<td class=xl67 width=64 style='border-top:none;border-left:none;width:48pt'>綜合一組</td>",
            "<td class=xl67 width=112 style='border-top:none;border-left:none;width:84pt'>測試基層主管2</td>",
            "<td class=xl67 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "09:51:54</td>",
            "<td class=xl67 width=114 style='border-top:none;border-left:none;width:86pt'>簽收</td>",
            "<td class=xl67 width=157 style='border-top:none;border-left:none;width:118pt'>系統自動簽收</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl66 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>5</td>",
            "<td class=xl66 width=64 style='border-top:none;border-left:none;width:48pt'>綜合一組</td>",
            "<td class=xl66 width=112 style='border-top:none;border-left:none;width:84pt'>測試基層主管2</td>",
            "<td class=xl66 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "10:33:41</td>",
            "<td class=xl66 width=114 style='border-top:none;border-left:none;width:86pt'>承辦人(陳核案件)</td>",
            "<td class=xl66 width=157 style='border-top:none;border-left:none;width:118pt'>陳核:測試基層主管1</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl67 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>6</td>",
            "<td class=xl67 width=64 style='border-top:none;border-left:none;width:48pt'>綜合一組</td>",
            "<td class=xl67 width=112 style='border-top:none;border-left:none;width:84pt'>測試基層主管1</td>",
            "<td class=xl67 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "10:33:41</td>",
            "<td class=xl67 width=114 style='border-top:none;border-left:none;width:86pt'>簽收</td>",
            "<td class=xl67 width=157 style='border-top:none;border-left:none;width:118pt'>系統自動簽收</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl66 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>7</td>",
            "<td class=xl66 width=64 style='border-top:none;border-left:none;width:48pt'>綜合一組</td>",
            "<td class=xl66 width=112 style='border-top:none;border-left:none;width:84pt'>測試基層主管1</td>",
            "<td class=xl66 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "10:38:06</td>",
            "<td class=xl66 width=114 style='border-top:none;border-left:none;width:86pt'>承辦人(陳核案件)</td>",
            "<td class=xl66 width=157 style='border-top:none;border-left:none;width:118pt'>陳核:總工程師</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl67 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>8</td>",
            "<td class=xl67 width=64 style='border-top:none;border-left:none;width:48pt'>總工程室</td>",
            "<td class=xl67 width=112 style='border-top:none;border-left:none;width:84pt'>總工程師</td>",
            "<td class=xl67 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "10:42:01</td>",
            "<td class=xl67 width=114 style='border-top:none;border-left:none;width:86pt'>簽收</td>",
            "<td class=xl67 width=157 style='border-top:none;border-left:none;width:118pt'>　</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl66 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>9</td>",
            "<td class=xl66 width=64 style='border-top:none;border-left:none;width:48pt'>總工程室</td>",
            "<td class=xl66 width=112 style='border-top:none;border-left:none;width:84pt'>總工程師</td>",
            "<td class=xl66 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "10:45:27</td>",
            "<td class=xl66 width=114 style='border-top:none;border-left:none;width:86pt'>核稿主管(待核判)</td>",
            "<td class=xl66 width=157 style='border-top:none;border-left:none;width:118pt'>陳核:測試核稿主管2</td>",
            "</tr>",
            "<tr height=40 style='mso-height-source:userset;height:30.0pt'>",
            "<td height=40 class=xl67 width=47 style='height:30.0pt;border-top:none;",
            "width:35pt'>10</td>",
            "<td class=xl67 width=64 style='border-top:none;border-left:none;width:48pt'>副署長室</td>",
            "<td class=xl67 width=112 style='border-top:none;border-left:none;width:84pt'>測試核稿主管2</td>",
            "<td class=xl67 width=106 style='border-top:none;border-left:none;width:80pt'>104/12/23",
            "<br>",
            "10:48:53</td>",
            "<td class=xl67 width=114 style='border-top:none;border-left:none;width:86pt'>簽收</td>",
            "<td class=xl67 width=157 style='border-top:none;border-left:none;width:118pt'>　</td>",
            "</tr>",
            "</table>"

        ].join(""),
        styleHtmlContent: true
    }
});