/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../src",
  "Ext-more": "../src/core/Ext-more.js",
  "Ext.Boot": ".sencha/app/Boot.js",
  "Ext.DomHelper": "../src/dom/Helper.js",
  "Ext.DomQuery": "../src/dom/Query.js",
  "Ext.Element-alignment": "../src/dom/Element.alignment.js",
  "Ext.Element-all": "../src/dom/Element.traversal.js",
  "Ext.Element-insertion": "../src/dom/Element.insertion.js",
  "Ext.Element-position": "../src/dom/Element.position.js",
  "Ext.Element-static": "../src/dom/Element.static.js",
  "Ext.Element-style": "../src/dom/Element.style.js",
  "Ext.Element-traversal": "../src/dom/Element.traversal.js",
  "Ext.cmd": "../../bin/Sencha/Cmd/6.2.0.103/plugins/src",
  "Ext.core.DomQuery": "../src/dom/Query.js",
  "Ext.device.Purchases.Product": "../src/device/purchases/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "../src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.Entry": "../src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.FileEntry": "../src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.FileSystem": "../src/device/filesystem/Sencha.js",
  "Ext.device.purchases.Purchase": "../src/device/purchases/Sencha.js",
  "Ext.device.sqlite.Database": "../src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSet": "../src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSetRowList": "../src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLTransaction": "../src/device/sqlite/Sencha.js",
  "HTMLPanel": "app/components/HTMLPanel.js",
  "ListItem": "app/form/FormNewDoc.js",
  "OA": "../oa/app",
  "app.components.JsonpX": "../oa/app/components/JsonpX.js"
});

Ext.ClassManager.addNameAlternateMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [],
  "Ext.BingMap": [],
  "Ext.Button": [],
  "Ext.Component": [
    "Ext.lib.Component"
  ],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "Ext.lib.Container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [
    "Ext.EventedBase"
  ],
  "Ext.Img": [],
  "Ext.ItemCollection": [],
  "Ext.Label": [],
  "Ext.LoadMask": [],
  "Ext.Map": [],
  "Ext.Mask": [],
  "Ext.Media": [],
  "Ext.Menu": [],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "Ext.lib.Panel"
  ],
  "Ext.ProgressIndicator": [],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [],
  "Ext.Sheet": [],
  "Ext.Sortable": [],
  "Ext.Spacer": [],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [],
  "Ext.TitleBar": [],
  "Ext.Toast": [],
  "Ext.Toolbar": [],
  "Ext.Video": [],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "Ext.Carousel"
  ],
  "Ext.carousel.Indicator": [
    "Ext.Carousel.Indicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [],
  "Ext.data.JsonP": [
    "Ext.util.JSONP"
  ],
  "Ext.data.JsonStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.ModelManager": [
    "Ext.ModelMgr",
    "Ext.ModelManager"
  ],
  "Ext.data.NodeInterface": [
    "Ext.data.Node"
  ],
  "Ext.data.NodeStore": [],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.Validations": [
    "Ext.data.validations"
  ],
  "Ext.data.association.Association": [
    "Ext.data.Association"
  ],
  "Ext.data.association.BelongsTo": [
    "Ext.data.BelongsToAssociation"
  ],
  "Ext.data.association.HasMany": [
    "Ext.data.HasManyAssociation"
  ],
  "Ext.data.association.HasOne": [
    "Ext.data.HasOneAssociation"
  ],
  "Ext.data.identifier.Sequential": [],
  "Ext.data.identifier.Simple": [],
  "Ext.data.identifier.Uuid": [],
  "Ext.data.plugin.Buffered": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.proxy.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.Sql": [
    "Ext.data.proxy.SQL"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dataview.DataView": [
    "Ext.DataView"
  ],
  "Ext.dataview.IndexBar": [
    "Ext.IndexBar"
  ],
  "Ext.dataview.List": [
    "Ext.List"
  ],
  "Ext.dataview.ListItemHeader": [],
  "Ext.dataview.NestedList": [
    "Ext.NestedList"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [],
  "Ext.dataview.component.ListItem": [],
  "Ext.dataview.component.SimpleListItem": [],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [
    "Ext.device.accelerometer.PhoneGap"
  ],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [
    "Ext.device.camera.PhoneGap"
  ],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [
    "Ext.device.capture.Simulator"
  ],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [
    "Ext.device.compass.PhoneGap"
  ],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [
    "Ext.device.connection.PhoneGap"
  ],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [
    "Ext.device.contacts.PhoneGap"
  ],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [
    "Ext.device.device.PhoneGap"
  ],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [
    "Ext.device.filesystem.PhoneGap"
  ],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [
    "Ext.device.geolocation.PhoneGap"
  ],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [
    "Ext.device.globalization.PhoneGap"
  ],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [
    "Ext.device.media.PhoneGap"
  ],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [
    "Ext.device.notification.PhoneGap"
  ],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [
    "Ext.device.splashscreen.PhoneGap"
  ],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [
    "Ext.device.storage.PhoneGap"
  ],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [
    "Ext.Direct"
  ],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.CompositeElement": [
    "Ext.CompositeElement"
  ],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [
    "Ext.EventObject"
  ],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.field.DatePicker": [
    "Ext.form.DatePicker"
  ],
  "Ext.field.DatePickerNative": [
    "Ext.form.DatePickerNative"
  ],
  "Ext.field.Email": [
    "Ext.form.Email"
  ],
  "Ext.field.Field": [
    "Ext.form.Field"
  ],
  "Ext.field.File": [],
  "Ext.field.FileInput": [],
  "Ext.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.field.Input": [],
  "Ext.field.Number": [
    "Ext.form.Number"
  ],
  "Ext.field.Password": [
    "Ext.form.Password"
  ],
  "Ext.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.field.Search": [
    "Ext.form.Search"
  ],
  "Ext.field.Select": [
    "Ext.form.Select"
  ],
  "Ext.field.Slider": [
    "Ext.form.Slider"
  ],
  "Ext.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.field.Text": [
    "Ext.form.Text"
  ],
  "Ext.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.field.TextAreaInput": [],
  "Ext.field.Toggle": [
    "Ext.form.Toggle"
  ],
  "Ext.field.Url": [
    "Ext.form.Url"
  ],
  "Ext.form.FieldSet": [],
  "Ext.form.Panel": [
    "Ext.form.FormPanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [],
  "Ext.fx.animation.Fade": [
    "Ext.fx.animation.FadeIn"
  ],
  "Ext.fx.animation.FadeOut": [],
  "Ext.fx.animation.Flip": [],
  "Ext.fx.animation.Pop": [
    "Ext.fx.animation.PopIn"
  ],
  "Ext.fx.animation.PopOut": [],
  "Ext.fx.animation.Slide": [
    "Ext.fx.animation.SlideIn"
  ],
  "Ext.fx.animation.SlideOut": [],
  "Ext.fx.animation.Wipe": [
    "Ext.fx.animation.WipeIn"
  ],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [],
  "Ext.fx.easing.EaseOut": [],
  "Ext.fx.easing.Linear": [],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [],
  "Ext.fx.layout.card.Cube": [],
  "Ext.fx.layout.card.Fade": [],
  "Ext.fx.layout.card.Flip": [],
  "Ext.fx.layout.card.Pop": [],
  "Ext.fx.layout.card.Reveal": [],
  "Ext.fx.layout.card.Scroll": [],
  "Ext.fx.layout.card.ScrollCover": [],
  "Ext.fx.layout.card.ScrollReveal": [],
  "Ext.fx.layout.card.Slide": [],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [],
  "Ext.layout.Card": [],
  "Ext.layout.Default": [],
  "Ext.layout.Fit": [],
  "Ext.layout.FlexBox": [],
  "Ext.layout.Float": [],
  "Ext.layout.HBox": [],
  "Ext.layout.VBox": [],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [
    "Ext.util.Observable"
  ],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "Ext.NavigationView"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Picker": [
    "Ext.Picker"
  ],
  "Ext.picker.Slot": [
    "Ext.Picker.Slot"
  ],
  "Ext.plugin.ListPaging": [],
  "Ext.plugin.PullRefresh": [],
  "Ext.plugin.SortableList": [],
  "Ext.scroll.Indicator": [
    "Ext.util.Indicator"
  ],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [
    "Ext.util.ScrollView"
  ],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [],
  "Ext.slider.Thumb": [],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "Ext.TabBar"
  ],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [
    "Ext.Tab"
  ],
  "Ext.table.Cell": [],
  "Ext.table.Row": [],
  "Ext.table.Table": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [
    "Ext.util.GeoLocation"
  ],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [
    "ParseHelper"
  ],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [],
  "Ext.ux.parse.Reader": [],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [],
  "Ext.ux.parse.association.Relation": [],
  "Ext.viewport.AndroidStock": [
    "Ext.viewport.Android"
  ],
  "Ext.viewport.Default": [],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [
    "Ext.viewport.WP"
  ],
  "HTMLPanel": [],
  "ListItem": [],
  "OA.client.Attach": [],
  "OA.client.Barrier": [],
  "OA.client.Cip": [],
  "OA.client.DocFlow": [],
  "OA.client.Editor": [],
  "OA.client.Exchange": [],
  "OA.client.File": [],
  "OA.client.Localforage": [],
  "OA.client.Lzwzip": [],
  "OA.client.Member": [],
  "OA.client.Phrase": [],
  "OA.client.Print": [],
  "OA.client.User": [],
  "OA.client.VI": [],
  "OA.client.WK": [],
  "OA.common.DIMgr": [],
  "OA.common.DateTimePicker": [
    "OA.common.DateTimePicker"
  ],
  "OA.common.Fields": [],
  "OA.common.FileMgr": [],
  "OA.common.Funcs": [],
  "OA.common.Global": [],
  "OA.common.InitParas": [],
  "OA.common.LocalPagingProxy": [],
  "OA.common.MouseWheelDrag": [],
  "OA.common.NestedListPaging": [],
  "OA.common.Paper": [],
  "OA.common.UrlMgr": [],
  "OA.common.Utils": [],
  "OA.common.VIMgr": [],
  "OA.components.JointPaper": [],
  "OA.components.MenuButton": [],
  "OA.components.Paper": [],
  "OA.components.PaperEditor": [],
  "OA.components.TouchTreeGrid": [],
  "OA.controller.Approve": [],
  "OA.controller.Login": [],
  "OA.controller.Menu": [],
  "OA.controller.Work": [],
  "OA.form.FormAddTable": [],
  "OA.form.FormAddress": [],
  "OA.form.FormApproveLevel": [],
  "OA.form.FormAttachCourse": [],
  "OA.form.FormAttachDesc": [],
  "OA.form.FormCaseNo": [],
  "OA.form.FormCaseNoTemplates": [],
  "OA.form.FormChange": [],
  "OA.form.FormChangeNumber": [],
  "OA.form.FormCoOrg": [],
  "OA.form.FormDocTemplates": [],
  "OA.form.FormEditMore": [],
  "OA.form.FormExport": [],
  "OA.form.FormFields": [],
  "OA.form.FormFileYear": [],
  "OA.form.FormFlowTip": [],
  "OA.form.FormImport": [],
  "OA.form.FormMore": [],
  "OA.form.FormMtAddress": [],
  "OA.form.FormMtContact": [],
  "OA.form.FormMtReason": [],
  "OA.form.FormNewDoc": [],
  "OA.form.FormOrg": [],
  "OA.form.FormOrgNotesOtherName": [],
  "OA.form.FormUrgencyLevels": [],
  "OA.form.FormAppellationSelf": [],
  "OA.form.FormOrgNo": [],
  "OA.form.FormOverprint": [],
  "OA.form.FormParallel": [],
  "OA.form.FormPopup": [],
  "OA.form.FormPreviewSetting": [],
  "OA.form.FormSecurity": [],
  "OA.form.FormSend": [],
  "OA.form.FormSentPaper": [],
  "OA.form.FormSetting": [],
  "OA.form.FormSimple": [],
  "OA.form.FormSpeed": [],
  "OA.form.FormTextArea": [],
  "OA.form.FormThesaurus": [],
  "OA.form.FormTodoWay": [],
  "OA.form.FormUser": [],
  "OA.form.PanelAttach": [],
  "OA.form.PanelChange": [],
  "OA.form.PanelOverprint": [],
  "OA.form.PanelReference": [],
  "OA.model.Attach": [],
  "OA.model.Barrier": [],
  "OA.model.CaseNo": [],
  "OA.model.Cip": [],
  "OA.model.Contact": [],
  "OA.model.Dcsn": [],
  "OA.model.Dep3Tree": [],
  "OA.model.Dept": [],
  "OA.model.DeptTree": [],
  "OA.model.DocFlow": [],
  "OA.model.Editor": [],
  "OA.model.Emp": [],
  "OA.model.Exchange": [],
  "OA.model.History": [],
  "OA.model.InitParas": [],
  "OA.model.Lzwzip": [],
  "OA.model.Octet": [],
  "OA.model.OverPrint": [],
  "OA.model.Paper": [],
  "OA.model.PaperInfo": [],
  "OA.model.Phrase": [],
  "OA.model.Print": [],
  "OA.model.Quote": [],
  "OA.model.Role": [],
  "OA.model.SignAction": [],
  "OA.model.Sticky": [],
  "OA.model.Sealinfo": [],
  "OA.model.TreeItem": [],
  "OA.model.User": [],
  "OA.model.VI": [],
  "OA.model.WorkFlow": [],
  "OA.model.seal.BASE": [],
  "OA.model.seal.TBPX": [],
  "OA.model.seal.TCHY": [],
  "OA.model.seal.TCQB": [],
  "OA.model.wk.AssignedNotice": [],
  "OA.model.wk.Attend": [],
  "OA.model.wk.BookLetter": [],
  "OA.model.wk.ExchangeNotice": [],
  "OA.model.wk.FactionLetter": [],
  "OA.model.wk.IssuesNotice": [],
  "OA.model.wk.Letter": [],
  "OA.model.wk.Letterhead": [],
  "OA.model.wk.LitigationReplyBook": [],
  "OA.model.wk.Meeting": [],
  "OA.model.wk.MoveNotice": [],
  "OA.model.wk.NoteSticky": [],
  "OA.model.wk.NoteEasy": [],
  "OA.model.wk.NoteOriginal": [],
  "OA.model.wk.Notes": [],
  "OA.model.wk.NotesOpinion": [],
  "OA.model.wk.Notice": [],
  "OA.model.wk.Order": [],
  "OA.model.wk.NotesAuditReports": [],
  "OA.model.wk.ProposalLetter": [],
  "OA.model.wk.ProposalNotice": [],
  "OA.model.wk.Publish": [],
  "OA.model.wk.RemindersNotice": [],
  "OA.model.wk.ReplyBook": [],
  "OA.model.wk.SurveyNotice": [],
  "OA.model.wk.TribunalBook": [],
  "OA.model.wk.tbpx.CalamityAdvanceNotice": [],
  "OA.model.wk.tbpx.NoteSticky": [],
  "OA.model.wk.tbpx.Notes": [],
  "OA.model.wk.tbpx.ReimbursedPayNotice": [],
  "OA.model.wk.tbpx.SecondAdvanceNotice": [],
  "OA.model.wk.EasyLetter": [],
  "OA.model.wk.EmailLetter": [],
  "OA.model.wk.tchy.Notes": [],
  "OA.store.Attach": [],
  "OA.store.Barrier": [],
  "OA.store.CaseNo": [],
  "OA.store.Cip": [],
  "OA.store.Contact": [],
  "OA.store.Dep3List": [],
  "OA.store.Dep3Tree": [],
  "OA.store.Dept": [],
  "OA.store.DeptList": [],
  "OA.store.DeptTree": [],
  "OA.store.DocFlow": [],
  "OA.store.Emp": [],
  "OA.store.History": [],
  "OA.store.Octet": [],
  "OA.store.OverPrint": [],
  "OA.store.Phrase": [],
  "OA.store.Quote": [],
  "OA.store.Role": [],
  "OA.store.SignAction": [],
  "OA.store.Sticky": [],
  "OA.store.Sealinfo": [],
  "OA.store.TaskAccordion": [],
  "OA.store.Tree": [],
  "OA.store.WorkFlow": [],
  "OA.view.ApproveFlow": [],
  "OA.view.ApproveSelect": [],
  "OA.view.ApproveWorkflow": [],
  "OA.view.CtnBulletin": [],
  "OA.view.CtnJointPaper": [],
  "OA.view.CtnPaper": [],
  "OA.view.CtnParallel": [],
  "OA.view.CtnPreview": [],
  "OA.view.CtnWorkflow": [],
  "OA.view.DocArea": [],
  "OA.view.DocForm": [],
  "OA.view.DocPaper": [],
  "OA.view.DocWorkflow": [],
  "OA.view.FlowOperation": [],
  "OA.view.Login": [],
  "OA.view.Main": [],
  "OA.view.MainEditor": [],
  "OA.view.MainWork": [],
  "OA.view.Menu": [],
  "OA.view.MenuEdition": [],
  "OA.view.MenuLeft": [],
  "OA.view.MenuList": [],
  "OA.view.MenuReceived": [],
  "OA.view.MenuVersion": [],
  "OA.view.StageApprove": [],
  "OA.view.StageEditor": [],
  "OA.view.StageEditorPopup": [],
  "OA.view.StageOfficialDoc": [],
  "OA.view.Suggestion": [],
  "OA.view.Welcome": [],
  "OA.view.Work": [],
  "app.components.JsonpX": []
});

Ext.ClassManager.addNameAliasMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [
    "widget.actionsheet"
  ],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [
    "widget.audio"
  ],
  "Ext.BingMap": [
    "widget.bingmap"
  ],
  "Ext.Button": [
    "widget.button"
  ],
  "Ext.Component": [
    "widget.component"
  ],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "widget.container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [],
  "Ext.Img": [
    "widget.image",
    "widget.img"
  ],
  "Ext.ItemCollection": [],
  "Ext.Label": [
    "widget.label"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.Map": [
    "widget.map"
  ],
  "Ext.Mask": [
    "widget.mask"
  ],
  "Ext.Media": [
    "widget.media"
  ],
  "Ext.Menu": [
    "widget.menu"
  ],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "widget.panel"
  ],
  "Ext.ProgressIndicator": [
    "widget.progressindicator"
  ],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [
    "widget.segmentedbutton"
  ],
  "Ext.Sheet": [
    "widget.sheet"
  ],
  "Ext.Sortable": [],
  "Ext.Spacer": [
    "widget.spacer"
  ],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [
    "widget.title"
  ],
  "Ext.TitleBar": [
    "widget.titlebar"
  ],
  "Ext.Toast": [],
  "Ext.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.Video": [
    "widget.video"
  ],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "widget.carousel"
  ],
  "Ext.carousel.Indicator": [
    "widget.carouselindicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [
    "data.field"
  ],
  "Ext.data.JsonP": [],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.Model": [],
  "Ext.data.ModelManager": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.Validations": [],
  "Ext.data.association.Association": [],
  "Ext.data.association.BelongsTo": [
    "association.belongsto"
  ],
  "Ext.data.association.HasMany": [
    "association.hasmany"
  ],
  "Ext.data.association.HasOne": [
    "association.hasone"
  ],
  "Ext.data.identifier.Sequential": [
    "data.identifier.sequential"
  ],
  "Ext.data.identifier.Simple": [
    "data.identifier.simple"
  ],
  "Ext.data.identifier.Uuid": [
    "data.identifier.uuid"
  ],
  "Ext.data.plugin.Buffered": [
    "plugin.storebuffered"
  ],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.Sql": [
    "proxy.sql"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dataview.DataView": [
    "widget.dataview"
  ],
  "Ext.dataview.IndexBar": [],
  "Ext.dataview.List": [
    "widget.list"
  ],
  "Ext.dataview.ListItemHeader": [
    "widget.listitemheader"
  ],
  "Ext.dataview.NestedList": [
    "widget.nestedlist"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [
    "widget.dataitem"
  ],
  "Ext.dataview.component.ListItem": [
    "widget.listitem"
  ],
  "Ext.dataview.component.SimpleListItem": [
    "widget.simplelistitem"
  ],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.CompositeElement": [],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "widget.checkboxfield"
  ],
  "Ext.field.DatePicker": [
    "widget.datepickerfield"
  ],
  "Ext.field.DatePickerNative": [
    "widget.datepickernativefield"
  ],
  "Ext.field.Email": [
    "widget.emailfield"
  ],
  "Ext.field.Field": [
    "widget.field"
  ],
  "Ext.field.File": [
    "widget.filefield"
  ],
  "Ext.field.FileInput": [
    "widget.fileinput"
  ],
  "Ext.field.Hidden": [
    "widget.hiddenfield"
  ],
  "Ext.field.Input": [
    "widget.input"
  ],
  "Ext.field.Number": [
    "widget.numberfield"
  ],
  "Ext.field.Password": [
    "widget.passwordfield"
  ],
  "Ext.field.Radio": [
    "widget.radiofield"
  ],
  "Ext.field.Search": [
    "widget.searchfield"
  ],
  "Ext.field.Select": [
    "widget.selectfield"
  ],
  "Ext.field.Slider": [
    "widget.sliderfield"
  ],
  "Ext.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.field.Text": [
    "widget.textfield"
  ],
  "Ext.field.TextArea": [
    "widget.textareafield"
  ],
  "Ext.field.TextAreaInput": [
    "widget.textareainput"
  ],
  "Ext.field.Toggle": [
    "widget.togglefield"
  ],
  "Ext.field.Url": [
    "widget.urlfield"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Panel": [
    "widget.formpanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [
    "animation.cube"
  ],
  "Ext.fx.animation.Fade": [
    "animation.fade",
    "animation.fadeIn"
  ],
  "Ext.fx.animation.FadeOut": [
    "animation.fadeOut"
  ],
  "Ext.fx.animation.Flip": [
    "animation.flip"
  ],
  "Ext.fx.animation.Pop": [
    "animation.pop",
    "animation.popIn"
  ],
  "Ext.fx.animation.PopOut": [
    "animation.popOut"
  ],
  "Ext.fx.animation.Slide": [
    "animation.slide",
    "animation.slideIn"
  ],
  "Ext.fx.animation.SlideOut": [
    "animation.slideOut"
  ],
  "Ext.fx.animation.Wipe": [],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [
    "easing.ease-in"
  ],
  "Ext.fx.easing.EaseOut": [
    "easing.ease-out"
  ],
  "Ext.fx.easing.Linear": [
    "easing.linear"
  ],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [
    "fx.layout.card.cover"
  ],
  "Ext.fx.layout.card.Cube": [
    "fx.layout.card.cube"
  ],
  "Ext.fx.layout.card.Fade": [
    "fx.layout.card.fade"
  ],
  "Ext.fx.layout.card.Flip": [
    "fx.layout.card.flip"
  ],
  "Ext.fx.layout.card.Pop": [
    "fx.layout.card.pop"
  ],
  "Ext.fx.layout.card.Reveal": [
    "fx.layout.card.reveal"
  ],
  "Ext.fx.layout.card.Scroll": [
    "fx.layout.card.scroll"
  ],
  "Ext.fx.layout.card.ScrollCover": [
    "fx.layout.card.scrollcover"
  ],
  "Ext.fx.layout.card.ScrollReveal": [
    "fx.layout.card.scrollreveal"
  ],
  "Ext.fx.layout.card.Slide": [
    "fx.layout.card.slide"
  ],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [
    "layout.tablebox"
  ],
  "Ext.layout.Card": [
    "layout.card"
  ],
  "Ext.layout.Default": [
    "layout.auto",
    "layout.default"
  ],
  "Ext.layout.Fit": [
    "layout.fit"
  ],
  "Ext.layout.FlexBox": [
    "layout.box"
  ],
  "Ext.layout.Float": [
    "layout.float"
  ],
  "Ext.layout.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "widget.navigationview"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Picker": [
    "widget.picker"
  ],
  "Ext.picker.Slot": [
    "widget.pickerslot"
  ],
  "Ext.plugin.ListPaging": [
    "plugin.listpaging"
  ],
  "Ext.plugin.PullRefresh": [
    "plugin.pullrefresh"
  ],
  "Ext.plugin.SortableList": [
    "plugin.sortablelist"
  ],
  "Ext.scroll.Indicator": [],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [
    "widget.slider"
  ],
  "Ext.slider.Thumb": [
    "widget.thumb"
  ],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.table.Cell": [
    "widget.tablecell"
  ],
  "Ext.table.Row": [
    "widget.tablerow"
  ],
  "Ext.table.Table": [
    "widget.table"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [
    "proxy.parse"
  ],
  "Ext.ux.parse.Reader": [
    "reader.parse"
  ],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [
    "association.pointer"
  ],
  "Ext.ux.parse.association.Relation": [
    "association.relation"
  ],
  "Ext.viewport.AndroidStock": [],
  "Ext.viewport.Default": [
    "widget.viewport"
  ],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [],
  "HTMLPanel": [],
  "ListItem": [],
  "OA.client.Attach": [
    "client.Attach"
  ],
  "OA.client.Barrier": [
    "client.Barrier"
  ],
  "OA.client.Cip": [
    "client.Cip"
  ],
  "OA.client.DocFlow": [
    "client.DocFlow"
  ],
  "OA.client.Editor": [
    "client.Editor"
  ],
  "OA.client.Exchange": [
    "client.Exchange"
  ],
  "OA.client.File": [
    "client.File"
  ],
  "OA.client.Localforage": [
    "client.Localforage"
  ],
  "OA.client.Lzwzip": [
    "client.Lzwzip"
  ],
  "OA.client.Member": [
    "client.Member"
  ],
  "OA.client.Phrase": [
    "client.Phrase"
  ],
  "OA.client.Print": [
    "client.Print"
  ],
  "OA.client.User": [
    "client.User"
  ],
  "OA.client.VI": [
    "client.VI"
  ],
  "OA.client.WK": [
    "client.WK"
  ],
  "OA.common.DIMgr": [
    "common.DIMgr"
  ],
  "OA.common.DateTimePicker": [
    "widget.datetimepicker"
  ],
  "OA.common.Fields": [
    "common.Fields"
  ],
  "OA.common.FileMgr": [
    "client.FileMgr"
  ],
  "OA.common.Funcs": [
    "common.Funcs"
  ],
  "OA.common.Global": [
    "common.Global"
  ],
  "OA.common.InitParas": [
    "common.InitParas"
  ],
  "OA.common.LocalPagingProxy": [
    "proxy.localpagingproxy"
  ],
  "OA.common.MouseWheelDrag": [],
  "OA.common.NestedListPaging": [
    "plugin.nestedlistpaging"
  ],
  "OA.common.Paper": [
    "common.Paper"
  ],
  "OA.common.UrlMgr": [
    "common.UrlMgr"
  ],
  "OA.common.Utils": [
    "common.Utils"
  ],
  "OA.common.VIMgr": [
    "common.VIMgr"
  ],
  "OA.components.JointPaper": [
    "widget.jointPaper"
  ],
  "OA.components.MenuButton": [
    "widget.menubutton"
  ],
  "OA.components.Paper": [
    "widget.cpaper"
  ],
  "OA.components.PaperEditor": [
    "widget.oaEditor"
  ],
  "OA.components.TouchTreeGrid": [
    "widget.touchtreegrid"
  ],
  "OA.controller.Approve": [],
  "OA.controller.Login": [],
  "OA.controller.Menu": [],
  "OA.controller.Work": [],
  "OA.form.FormAddTable": [
    "widget.FormAddTable"
  ],
  "OA.form.FormAddress": [
    "widget.FormAddress"
  ],
  "OA.form.FormApproveLevel": [
    "widget.FormApproveLevel"
  ],
  "OA.form.FormAttachCourse": [
    "widget.FormAttachCourse"
  ],
  "OA.form.FormAttachDesc": [
    "widget.FormAttachDesc"
  ],
  "OA.form.FormCaseNo": [
    "widget.FormCaseNo"
  ],
  "OA.form.FormCaseNoTemplates": [
    "widget.FormCaseNoTemplates"
  ],
  "OA.form.FormChange": [
    "widget.FormChange"
  ],
  "OA.form.FormChangeNumber": [
    "widget.FormChangeNumber"
  ],
  "OA.form.FormCoOrg": [
    "widget.FormCoOrg"
  ],
  "OA.form.FormDocTemplates": [
    "widget.FormDocTemplates"
  ],
  "OA.form.FormEditMore": [
    "widget.FormEditMore"
  ],
  "OA.form.FormExport": [
    "widget.FormExport"
  ],
  "OA.form.FormFields": [
    "widget.FormFields"
  ],
  "OA.form.FormFileYear": [
    "widget.FormFileYear"
  ],
  "OA.form.FormFlowTip": [
    "widget.FormFlowTip"
  ],
  "OA.form.FormImport": [
    "widget.FormImport"
  ],
  "OA.form.FormMore": [
    "widget.FormMore"
  ],
  "OA.form.FormMtAddress": [
    "widget.FormMtAddress"
  ],
  "OA.form.FormMtContact": [
    "widget.FormMtContact"
  ],
  "OA.form.FormMtReason": [
    "widget.FormMtReason"
  ],
  "OA.form.FormNewDoc": [
    "widget.FormNewDoc"
  ],
  "OA.form.FormOrg": [
    "widget.FormOrg"
  ],
  "OA.form.FormOrgNotesOtherName": [
    "widget.FormOrgNotesOtherName"
  ],
  "OA.form.FormUrgencyLevels": [
    "widget.FormUrgencyLevels"
  ],
  "OA.form.FormAppellationSelf": [
    "widget.FormAppellationSelf"
  ],
  "OA.form.FormOrgNo": [
    "widget.FormOrgNo"
  ],
  "OA.form.FormOverprint": [
    "widget.FormOverprint"
  ],
  "OA.form.FormParallel": [
    "widget.FormParallel"
  ],
  "OA.form.FormPopup": [
    "widget.FormPopup"
  ],
  "OA.form.FormPreviewSetting": [
    "widget.FormPreviewSetting"
  ],
  "OA.form.FormSecurity": [
    "widget.FormSecurity"
  ],
  "OA.form.FormSend": [
    "widget.FormSend"
  ],
  "OA.form.FormSentPaper": [
    "widget.FormSentPaper",
    "widget.FormSpentPaper"
  ],
  "OA.form.FormSetting": [
    "widget.FormSetting"
  ],
  "OA.form.FormSimple": [
    "widget.FormSimple"
  ],
  "OA.form.FormSpeed": [
    "widget.FormSpeed"
  ],
  "OA.form.FormTextArea": [
    "widget.FormTextArea"
  ],
  "OA.form.FormThesaurus": [
    "widget.FormThesaurus"
  ],
  "OA.form.FormTodoWay": [
    "widget.FormTodoWay"
  ],
  "OA.form.FormUser": [
    "widget.FormUser"
  ],
  "OA.form.PanelAttach": [
    "widget.PanelAttach"
  ],
  "OA.form.PanelChange": [
    "widget.PanelChange"
  ],
  "OA.form.PanelOverprint": [
    "widget.PanelOverprint"
  ],
  "OA.form.PanelReference": [
    "widget.PanelReference"
  ],
  "OA.model.Attach": [],
  "OA.model.Barrier": [
    "model.Barrier"
  ],
  "OA.model.CaseNo": [
    "model.CaseNo"
  ],
  "OA.model.Cip": [],
  "OA.model.Contact": [],
  "OA.model.Dcsn": [],
  "OA.model.Dep3Tree": [],
  "OA.model.Dept": [
    "model.Dept"
  ],
  "OA.model.DeptTree": [],
  "OA.model.DocFlow": [],
  "OA.model.Editor": [
    "model.Editor"
  ],
  "OA.model.Emp": [],
  "OA.model.Exchange": [],
  "OA.model.History": [],
  "OA.model.InitParas": [],
  "OA.model.Lzwzip": [
    "model.Lzwzip"
  ],
  "OA.model.Octet": [],
  "OA.model.OverPrint": [],
  "OA.model.Paper": [],
  "OA.model.PaperInfo": [],
  "OA.model.Phrase": [
    "model.Phrase"
  ],
  "OA.model.Print": [],
  "OA.model.Quote": [],
  "OA.model.Role": [
    "model.Role"
  ],
  "OA.model.SignAction": [
    "model.SignAction"
  ],
  "OA.model.Sticky": [],
  "OA.model.Sealinfo": [],
  "OA.model.TreeItem": [],
  "OA.model.User": [
    "model.User"
  ],
  "OA.model.VI": [
    "model.VI"
  ],
  "OA.model.WorkFlow": [],
  "OA.model.seal.BASE": [],
  "OA.model.seal.TBPX": [],
  "OA.model.seal.TCHY": [],
  "OA.model.seal.TCQB": [],
  "OA.model.wk.AssignedNotice": [],
  "OA.model.wk.Attend": [],
  "OA.model.wk.BookLetter": [],
  "OA.model.wk.ExchangeNotice": [],
  "OA.model.wk.FactionLetter": [],
  "OA.model.wk.IssuesNotice": [],
  "OA.model.wk.Letter": [],
  "OA.model.wk.Letterhead": [],
  "OA.model.wk.LitigationReplyBook": [],
  "OA.model.wk.Meeting": [],
  "OA.model.wk.MoveNotice": [],
  "OA.model.wk.NoteSticky": [],
  "OA.model.wk.Notes": [],
  "OA.model.wk.NotesOpinion": [],
  "OA.model.wk.Notice": [],
  "OA.model.wk.Order": [],
  "OA.model.wk.NotesAuditReports": [],
  "OA.model.wk.ProposalLetter": [],
  "OA.model.wk.ProposalNotice": [],
  "OA.model.wk.Publish": [],
  "OA.model.wk.RemindersNotice": [],
  "OA.model.wk.ReplyBook": [],
  "OA.model.wk.SurveyNotice": [],
  "OA.model.wk.TribunalBook": [],
  "OA.model.wk.tbpx.CalamityAdvanceNotice": [],
  "OA.model.wk.tbpx.NoteSticky": [],
  "OA.model.wk.tbpx.Notes": [],
  "OA.model.wk.tbpx.ReimbursedPayNotice": [],
  "OA.model.wk.tbpx.SecondAdvanceNotice": [],
  "OA.model.wk.EasyLetter": [],
  "OA.model.wk.EmailLetter": [],
  "OA.model.wk.tchy.Notes": [],
  "OA.store.Attach": [
    "store.Attach"
  ],
  "OA.store.Barrier": [
    "store.Barrier"
  ],
  "OA.store.CaseNo": [
    "store.CaseNo"
  ],
  "OA.store.Cip": [
    "store.Cip"
  ],
  "OA.store.Contact": [
    "store.Contact"
  ],
  "OA.store.Dep3List": [
    "store.Dep3List"
  ],
  "OA.store.Dep3Tree": [],
  "OA.store.Dept": [
    "store.Dept"
  ],
  "OA.store.DeptList": [
    "store.DeptList"
  ],
  "OA.store.DeptTree": [],
  "OA.store.DocFlow": [
    "store.DocFlow"
  ],
  "OA.store.Emp": [
    "store.Emp"
  ],
  "OA.store.History": [
    "store.History"
  ],
  "OA.store.Octet": [
    "store.Octet"
  ],
  "OA.store.OverPrint": [
    "store.OverPrint"
  ],
  "OA.store.Phrase": [
    "store.Phrase"
  ],
  "OA.store.Quote": [
    "store.Quote"
  ],
  "OA.store.Role": [
    "store.Role"
  ],
  "OA.store.SignAction": [
    "store.SignAction"
  ],
  "OA.store.Sticky": [
    "store.Sticky"
  ],
  "OA.store.Sealinfo": [
    "store.Sealinfo"
  ],
  "OA.store.TaskAccordion": [
    "store.TaskAccordion"
  ],
  "OA.store.Tree": [
    "store.TreeStore"
  ],
  "OA.store.WorkFlow": [
    "store.WorkFlow"
  ],
  "OA.view.ApproveFlow": [
    "widget.approveFlow"
  ],
  "OA.view.ApproveSelect": [
    "widget.approveSelect"
  ],
  "OA.view.ApproveWorkflow": [
    "widget.approveWorkflow"
  ],
  "OA.view.CtnBulletin": [
    "widget.ctnBulletin"
  ],
  "OA.view.CtnJointPaper": [
    "widget.ctnJointPaper"
  ],
  "OA.view.CtnPaper": [
    "widget.ctnPaper"
  ],
  "OA.view.CtnParallel": [
    "widget.ctnParallel"
  ],
  "OA.view.CtnPreview": [
    "widget.ctnPreview"
  ],
  "OA.view.CtnWorkflow": [
    "widget.ctnWorkflow"
  ],
  "OA.view.DocArea": [
    "widget.docArea"
  ],
  "OA.view.DocForm": [
    "widget.docForm"
  ],
  "OA.view.DocPaper": [
    "widget.docPaper"
  ],
  "OA.view.DocWorkflow": [
    "widget.docWorkflow"
  ],
  "OA.view.FlowOperation": [
    "widget.FlowOperation",
    "widget.flowOperation"
  ],
  "OA.view.Login": [
    "widget.loginview"
  ],
  "OA.view.Main": [
    "widget.oamain"
  ],
  "OA.view.MainEditor": [
    "widget.mainEditor"
  ],
  "OA.view.MainWork": [
    "widget.mainWork"
  ],
  "OA.view.Menu": [
    "widget.oamenu"
  ],
  "OA.view.MenuEdition": [
    "widget.menuEdition"
  ],
  "OA.view.MenuLeft": [
    "widget.menuLeft"
  ],
  "OA.view.MenuList": [
    "widget.menuList"
  ],
  "OA.view.MenuReceived": [
    "widget.menuReceived"
  ],
  "OA.view.MenuVersion": [
    "widget.menuVersion"
  ],
  "OA.view.StageApprove": [
    "widget.StageApprove"
  ],
  "OA.view.StageEditor": [
    "widget.StageEditor"
  ],
  "OA.view.StageEditorPopup": [
    "widget.StageEditorPopup"
  ],
  "OA.view.StageOfficialDoc": [
    "widget.StageOfficialDoc"
  ],
  "OA.view.Suggestion": [
    "widget.suggestion"
  ],
  "OA.view.Welcome": [
    "widget.ol"
  ],
  "OA.view.Work": [
    "widget.oawork"
  ],
  "app.components.JsonpX": [
    "reader.jsonpx"
  ]
});


/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */


